// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izkmemlswyvvvupcnpxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6a21lbWxzd3l2dnZ1cGNucHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDYwOTcsImV4cCI6MjA2MTQyMjA5N30.4D1iCrXHGWl1LstS0IfEquTuJGhc2tAGsQTbR-zq8bU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);