
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izkmemlswyvvvupcnpxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6a21lbWxzd3l2dnZ1cGNucHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDYwOTcsImV4cCI6MjA2MTQyMjA5N30.4D1iCrXHGWl1LstS0IfEquTuJGhc2tAGsQTbR-zq8bU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create custom types for tables not in auto-generated types
type CustomDatabase = Database & {
  public: {
    Tables: {
      admin_settings: {
        Row: {
          id: string;
          settings: any;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          settings: any;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          settings?: any;
          updated_at?: string | null;
        };
      };
      wallets: {
        Row: {
          id: string;
          user_id: string;
          balance: number;
          auto_pay: boolean;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          balance: number;
          auto_pay: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          balance?: number;
          auto_pay?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      wallet_transactions: {
        Row: {
          id: string;
          user_id: string;
          amount: number;
          type: string;
          description: string;
          created_at: string;
          status: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          amount: number;
          type: string;
          description: string;
          created_at?: string;
          status: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          amount?: number;
          type?: string;
          description?: string;
          created_at?: string;
          status?: string;
        };
      };
    } & Database['public']['Tables'];
  };
};

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
